add_newline = false

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[character]
format = ' $symbol '

[cmake]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[cmd_duration]
format = '\[[⏱ $duration ]($style)\]'
disabled = true

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[dart]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[deno]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[directory]
format = ':[$path]($style)[$read_only]($read_only_style)'
truncation_symbol = "…/"

[docker_context]
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'
disabled = true

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
disabled = true

[elm]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[erlang]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[helm]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[hostname]
format = '@[$hostname]($style)'

[java]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[jobs]
format = '[$symbol$number]($style)'

[julia]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[kotlin]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[line_break]
disabled = true

[lua]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nim]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
disabled = true

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[perl]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[php]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[purescript]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[python]
#format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
format='(\[[$virtualenv]($style)\])'

[red]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[rlang]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[ruby]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[rust]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[scala]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[swift]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '[$user]($style)'
show_always = true

[vagrant]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[vlang]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[zig]
format = '\[[$symbol($version)]($style)\]'
disabled = true
